<?php

// usm & spk ujcj & ckaj

// Name of your MySql server
$server = "localhost";
// Database username
$user = "username";
// Database password
$password = "password";
// Name of the database
$database = "ckaj";

$query = $_POST['query'];
$kpvar = $_POST['kpvar']; 
$unit = $_POST['unit'];
$tahun = $_POST['tahun'];
$bulan = $_POST['bulan'];
$minggu = $_POST['minggu'];

$kp_s = $_POST['kp_s']; 
$OIC = $_POST['OIC'];
$startDate = $_POST['startDate'];
?>